# Mod metadata — shared across all versions
mod.id      = "crosspatch"
mod.name    = "crossPatch"
mod.version = "0.2.8"
mod.group   = "com.rs256.crossPatch"

# deps. is used dependency resolving,
# build. is used build jar resource prosessing
deps.fabric_loader  = "0.19.2"
build.fabric_loader = ">=0.19.2"
deps.mixinsquared   = "0.3.7-beta.1"
deps.configurate    = "4.1.2"
deps.typesafe_config = "1.4.2"
deps.geantyref      = "1.3.13"

build.fabric_api    = "*"
build.modmenu       = "*"
build.malilib       = "*"
build.litematica    = "*"
build.itemscroller  = "*"
build.tweakermore   = "*"
build.flashback     = "*"
build.bobby         = "*"

publish.modrinth   = "XXXXXXXX"
publish.curseforge = "XXXXXXXX"
publish.github     = "RS-256/CrossPatch"

# Per-version properties
["1.21.11"]
deps.fabric_api = "0.141.3+1.21.11"
mod.mc_dep      = "1.21.11"
mod.mc_title    = "1.21.11"
mod.mc_targets  = "1.21.11"
# build.fabric_api = "0.141.3+1.21.11"     # additional if needed

deps.modmenu = "17.0.0"
deps.malilib  = "0.27.9"
deps.litematica  = "0.26.5"
deps.itemscroller  = "0.30.3"
deps.tweakermore = "3.31.0"
deps.flashback = "AGkqd25Y"
deps.bobby = "y6wx9vV9"
deps.lattice = "1.3.1"

["26.1.2"]
deps.fabric_api = "0.150.0+26.1.2"
mod.mc_dep      = "26.1.2"
mod.mc_title    = "26.1.2"
mod.mc_targets  = "26.1.2"

deps.modmenu = "18.0.0-beta.1"
deps.malilib  = "0.28.3"
deps.litematica  = "0.27.3"
deps.itemscroller  = "0.31.2"
deps.tweakermore = "3.31.0"
deps.flashback = "XRtfepgi"
deps.bobby = "njaTBYvt"
deps.lattice = "2.0.1+26.1"
