# Mod metadata — shared across all versions
mod.id      = "crosspatch"
mod.name    = "crossPatch"
mod.version = "0.3.8"
mod.group   = "com.rs256.crossPatch"

# deps. is used dependency resolving,
# build. is used build jar resource prosessing
deps.fabric_loader  = "0.19.5"
build.fabric_loader = ">=0.19.5"

build.fabric_api    = "*"
build.modmenu       = "*"
build.malilib       = "*"
build.litematica    = "*"
build.itemscroller  = "*"
build.tweakermore   = "*"

publish.modrinth   = "BVBbOmXq"
publish.curseforge = "XXXXXXXX"
publish.github     = "RS-256/CrossPatch"

# Per-version properties
["1.21.11"]
deps.fabric_api = "0.141.6+1.21.11"
mod.mc_dep      = "1.21.11"
mod.mc_title    = "1.21.11"
mod.mc_targets  = "1.21.11"
# build.fabric_api = "0.141.3+1.21.11"     # additional if needed

deps.modmenu = "17.0.1-beta.1"
deps.malilib  = "0.27.19"
deps.litematica  = "0.26.14"
deps.itemscroller  = "0.30.5"  # 0.30.6 tag fails to build on JitPack
deps.tweakermore = "3.33.2"

["26.1.2"]
deps.fabric_api = "0.155.2+26.1.2"
mod.mc_dep      = "26.1.2"
mod.mc_title    = "26.1.2"
mod.mc_targets  = "26.1.2"

deps.modmenu = "18.0.0"
deps.malilib  = "0.28.11"
deps.litematica  = "0.27.12"
deps.itemscroller  = "0.31.5"
deps.tweakermore = "3.33.2"

["26.2"]
deps.fabric_api = "0.159.0+26.2"
mod.mc_dep      = "26.2"
mod.mc_title    = "26.2"
mod.mc_targets  = "26.2"

deps.modmenu = "20.0.1"
deps.malilib  = "0.29.5"
deps.litematica  = "0.28.6"
deps.itemscroller  = "0.32.1"
deps.tweakermore = "3.33.2"

["26.3"]
deps.fabric_api = "0.161.0+26.3"
mod.mc_dep      = "26.3"
mod.mc_title    = "26.3"
mod.mc_targets  = "26.3"

deps.modmenu = "21.0.0"
deps.malilib  = "0.30.1"
deps.litematica  = "0.29.0"
deps.itemscroller  = "0.33.0"
deps.tweakermore = "3.33.3-beta.1"
